version: 1.0

LLM_model:
    model: "qwen/qwen3-30b-a3b:free"
    url: "https://openrouter.ai/api/v1"
    api_key: "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"

database:
    user: user
    password: passw
    database: db
    host: "127.0.0.1"
    port: 5440